---
version: '2'
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    volumes:
      - /opt/appdata/plex:/config
      - /mnt/storage:/data
    network_mode: host
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
  plexpy:
    image: linuxserver/plexpy
    container_name: plexpy
    depends_on:
      - plex
    volumes:
      - /opt/appdata/plexpy:/config
      - /opt/appdata/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
    ports:
      - 27029:8181
    links:
      - plex
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
  portainer:
    image: portainer/portainer
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - /opt/appdata/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart:
      always
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    links:
      - jackett:jackett
      - qbittorrent:qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /opt/appdata/radarr:/config
      - /mnt/storage/Videos:/movies
      - /mnt/storage/downloads/qbittorrent:/downloads
    ports:
      - 7878:7878
    mem_limit: 4096m
    restart: unless-stopped
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
      - WEBUI_PORT=9999
    volumes:
      - /opt/appdata/qbittorrent:/config
      - /mnt/storage/downloads/qbittorrent:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 9999:9999
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /opt/appdata/jackett:/config
      - /home/mark/downloads/jackett:/downloads
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9117:9117
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    links:
      - jackett:jackett
      - qbittorrent:qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /opt/appdata/sonarr:/config
      - /mnt/storage/Videos/Tv:/tv
      - /mnt/storage/downloads/qbittorrent:/downloads
    ports:
      - 8989:8989
    mem_limit: 4096m
    restart: unless-stopped
  plexpy:
    image: linuxserver/plexpy
    container_name: plexpy
    depends_on:
      - plex
    volumes:
      - /opt/appdata/plexpy:/config
      - /opt/appdata/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
    ports:
      - 27029:8181
    links:
      - plex
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
  plexrequests:
    image: linuxserver/plexrequests
    container_name: plexrequests
    depends_on:
      - plex
    volumes:
      - /opt/appdata/plexrequests:/config
      - /mnt/storage/tv:/tv
    ports:
      - 27026:3000
    links:
      - plex
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    volumes:
      - /opt/appdata/nzbget/config:/config
      - /opt/downloads:/downloads
      - /mnt/disk1/downloads/complete:/downloads/complete
    ports:
      - 27020:6789
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    depends_on:
      - nzbget
    volumes:
      - /opt/appdata/sonarr:/config
      - /mnt/storage/tv:/tv
      - /mnt/disk1/downloads/complete/tv:/downloads
      - /mnt/storage/downloads/complete/tv_import:/tv_import
    ports:
      - 27021:8989
    links:
      - nzbget
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
  couchpotato:
    image: linuxserver/couchpotato
    container_name: couchpotato
    depends_on:
      - nzbget
    volumes:
      - /opt/appdata/couchpotato:/config
      - /mnt/disk1/downloads/complete/movies:/downloads
      - /mnt/storage/movies:/movies
    ports:
      - 27022:5050
    links:
      - nzbget
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
  smokeping:
    image: linuxserver/smokeping
    container_name: smokeping
    volumes:
      - /opt/appdata/smokeping/config:/config
      - /opt/appdata/smokeping/data:/data
    ports:
      - 27025:80
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    restart: always
  libresonic:
    image: linuxserver/libresonic
    container_name: libresonic
    ports:
      - 4040:4040
    volumes:
      - /opt/appdata/libresonic:/config
      - /mnt/storage/music/flac:/music/flac
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - CONTEXT_PATH=sonic
    restart:
      always
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    volumes:
      - /opt/appdata/influxdb:/var/lib/influxdb
    restart:
      always
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3001:3000
    volumes:
      - /opt/appdata/grafana:/var/lib/grafana
    restart:
      always
